add a basic setup
Yonasle/Leaderboard pull request #1
Opened 2023-08-31 21:06 UTC by Yonasle

-Leaderboard using API Setup
-ES6 Feature implemented
-Best Practice HTML , CSS and JavaScript implemented 
-Professional Readme file
-Linter configured

2023-08-31 22:18 UTC, jerryowusu requested changes
Hi @Yonasle 

Good job so far!
Your project is looking fantastic so far :star_struck: 

However, there are few changes you need to make in order to move on to the next level :sunglasses:

![so close](https://github.com/Yonasle/Leaderboard/assets/65233860/e435e16d-649f-4798-8cba-c44a777f7b58)


## Highlights
Used gitflow :+1: 
Great job so far :+1: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-31 22:18 UTC, jerryowusu commented on package.json
> +  },
In the scripts you should have values that can help you run and start the app. Currently it is difficult to start the app using npm since an error shown below appears when you use npm build or npm run dev/start (error: missing scripts)

Kindly ensure that there is no error when running the app.

![Screenshot from 2023-08-31 21-38-43](https://github.com/Yonasle/Leaderboard/assets/65233860/85606e18-a433-4c65-8a22-f6c74e30ee91)

2023-08-31 22:18 UTC, jerryowusu commented on src/index.html
> +  </table>
As shown in the given [wireframe](https://github.com/microverseinc/curriculum-javascript/blob/main/leaderboard/images/leaderboard_wireframe.png), you need to populate some data so that it will display when you open the app. 
Also kindly ensure that your design accurately matches the wireframe. :pray:

2023-08-31 22:18 UTC, jerryowusu commented on README.md
> +This project is [MIT](./LICENSE) licensed.
Kindly provide a valid link to the license file here since the provided link is not working and leads to a `404- page not found`

2023-09-01 07:17 UTC, Cabraham1 approved these changes
Hi @Yonasle  , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media1.giphy.com/media/3kuSo744UIPJjcJUEn/giphy.gif"/>

## Highlights
📌 No Linters error ✅
📌 Descriptive pull request✅
📌 Good commit messages ✅
📌 Professional README file ✅

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-01 07:27 UTC, merged